services:
  # Mock Bank API
  - type: web
    name: mock-bank-api
    runtime: node
    plan: free
    buildCommand: "cd upi-recon-system/mock-bank-api && npm install"
    startCommand: "cd upi-recon-system/mock-bank-api && npm start"
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production

  # UPI Payment System
  - type: web
    name: upi-payment-system
    runtime: node
    plan: free
    buildCommand: "cd upi-recon-system/upiPaymentSystem && npm install"
    startCommand: "cd upi-recon-system/upiPaymentSystem && npm start"
    envVars:
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://paysync-frontend.onrender.com
      - key: BANK_API_URL
        value: https://mock-bank-api.onrender.com/api/v1/bank
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

  # Reconciliation Engine (Background Worker)
  - type: web
    name: reconciliation-engine
    runtime: node
    plan: free
    buildCommand: "cd upi-recon-system/upi-reconciliation && npm install"
    startCommand: "cd upi-recon-system/upi-reconciliation && npm start"
    envVars:
      - key: PORT
        value: 8001
      - key: MONGODB_URI
        sync: false
      - key: UPI_API_URL
        value: https://upi-payment-system.onrender.com/api/v1
      - key: PUBLIC_VAPID_KEY
        value: BOv58v_3DS9gYtNJbqyArK66saENo7rSWoJnXdB177GHlJdrDyWqMc0Kh1_O722rFoiKlOQL8eWY7pq0c5ntrmo
      - key: PRIVATE_VAPID_KEY
        value: My7PyfeYqEdbPUJkDdqaj5Um0KvvVFzdF7t9_LVPeBk
      - key: VAPID_EMAIL
        value: mailto:tanishadeshmukh44@gmail.com
      - key: BANK_API_URL
        value: https://mock-bank-api.onrender.com/api/v1/bank
      - key: NODE_ENV
        value: production

  # React Frontend
  - type: web
    name: paysync-frontend
    runtime: static
    buildCommand: "cd upi-recon-system/react-app && npm install && npm run build"
    staticPublishPath: upi-recon-system/react-app/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_UPI_API_URL
        value: https://upi-payment-system.onrender.com/api/v1
      - key: VITE_RECON_API_URL
        value: https://reconciliation-engine.onrender.com/api/v1
      - key: VITE_MOCK_BANK_API_URL
        value: https://mock-bank-api.onrender.com/api/v1
      - key: VITE_VAPID_PUBLIC_KEY
        fromService:
          type: web
          name: reconciliation-engine
          envVarKey: PUBLIC_VAPID_KEY

